name: Validate documentation
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdoc
    - name: Run pdoc
      run: |
        PYTHONWARNINGS='error::UserWarning' pdoc --output-dir docs grilops '!grilops.(fastz3|quadtree)'
